---
name: Test

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
#          - "2.0"
#          - "2.1"
#          - "2.2"
#          - "2.3"
#          - "2.4"
#          - "2.5"
#          - "2.6.3"
#          - "2.6.7"
          - "2.7.8"
    env:
      TEST_ALL: 1
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
#      - run: gem install rubygems-update -v '<= 2.7.8'
#        if: ${{ matrix.ruby == '2.0' || matrix.ruby == '2.1' || matrix.ruby == '2.2' }}
#      - run: gem update --system 2.7.8
#        if: ${{ matrix.ruby == '2.0' || matrix.ruby == '2.1' || matrix.ruby == '2.2' }}
#      - run: gem install rubygems-update -v '<= ${{matrix.ruby}}'
#        if: ${{ matrix.ruby != '2.0' && matrix.ruby != '2.1' && matrix.ruby != '2.2' }}
#      - run: gem update --system
#        if: ${{ matrix.ruby != '2.0' && matrix.ruby != '2.1' && matrix.ruby != '2.2' }}
      - run: gem install bundler -v 1.17.3
      - run: bundle install
      - run: bin/rake build format_json && git status -s && [[ -z $(git status -s) ]]
      - run: bundle exec rspec
